---
kind: ConfigMap
apiVersion: v1
metadata:
  name: macvtap-deviceplugin-config
  namespace: cluster-network-addons
data:
  DP_MACVTAP_CONF: |
    [ {
        "name" : "tink",
        "master" : "eth0",
        "mode": "bridge",
        "capacity" : 50
    } ]