---
kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: tink
  annotations:
    k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/tink
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "tink",
      "type": "macvtap",
      "mtu": 1500
    }'